name: Build/Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build and run tests
        run: |
          nix develop .# -c zig build test

      - name: Run example executable
        run: |
          export NIX_PATH="nixpkgs=$(nix flake metadata nixpkgs --json | jq -r .path)"
          nix develop .# -c zig build run
